spring:
  application:
    name: flip-url-shortener
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/shortener
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
      maximum-pool-size: 100
      connection-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      data-source-properties:
        connectTimeout: 60
        loginTimeout: 60
        socketTimeout: 70
        cancelSignalTimeout: 10
        tcpKeepAlive: true
        queryTimeout: 60
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      jakarta.persistence.query.timeout: 60000
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  task:
    execution:
      pool:
        core-size: 8
        max-size: 32
        queue-capacity: 100
    scheduling:
      pool:
        size: 2
  flyway:
    enabled: true
    baseline-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 1h
      cache-null-values: false

app:
  url-limit: 10000
  short-code-length: 8
  max-url-length: 2048
  maintenance:
    rate: PT1M
  generator:
    name: base62Generator

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

resilience4j:
  retry:
    retry-aspect-order: 1
    instances:
      dbRetry:
        max-attempts: 10
        wait-duration: 50ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.orm.ObjectOptimisticLockingFailureException
      shortenRetry:
        max-attempts: 5
        wait-duration: 100ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.dao.DataIntegrityViolationException
          - org.springframework.orm.ObjectOptimisticLockingFailureException
  ratelimiter:
    instances:
      shortenLimit:
        limit-for-period: 10000
        limit-refresh-period: 3s
        timeout-duration: 0ms
        register-health-indicator: true

logging:
  loki:
    url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    com.mrakin: DEBUG

server:
  port: 8080
